### ISSUE TITLE
Please, integrate web-installer to deploy scripts

### ISSUE THREAD

**Issue by gratuxri** [nextcloud/web-installer#34]
If you show me where is you "make release" scripts, maybe I can do it.

**Comment by kesselb** [comment]
[For now the release scripts are not published](https://help.nextcloud.com/t/build-bzip-and-package-from-git/58341/2) :disappointed: 

What you could do to improve the situation is to change `NC_VERSION` to `NC_MAJOR_VERSION`. We should look into this file for the major releases because sometimes there are new dependencies.

https://github.com/nextcloud/web-installer/blob/d586bcc973c348390dfac8f0c5632062f216dafd/setup-nextcloud.php#L147

https://download.nextcloud.com/server/releases/ there is a file "latest-16" or "latest-17" which always points to the latest version.

https://github.com/nextcloud/web-installer/blob/d586bcc973c348390dfac8f0c5632062f216dafd/setup-nextcloud.php#L687

I think it's okay to show Nextcloud 17 here. If you want to concrete version number we have to dig a bit.

**Comment by gratuxri** [comment]
web-installer is usefull for first installation and I mean in most cases it make no sense to install not the latest version. If someone want to have latest-16 or older, then he can change it in downloaded file. If it's new dependencies for installation, then it make more sense, that people write issue here about it.
