### ISSUE TITLE
Push updated web-installer to https://nextcloud.com/install/ page

### ISSUE THREAD

**Issue by DBJRdev** [nextcloud/web-installer#38]
The web installer that is offered on nextcloud.com/install still triggers the download of Nextcloud 16.0.3 (instead of "latest"). So it seems it was forgotten to transfer this version from here to the Nextcloud website.

**Comment by gratuxri** [comment]
I mean this link: https://download.nextcloud.com/server/installer/setup-nextcloud.php

**Comment by DBJRdev** [comment]
Two months later, still the same situation: while Nextcloud 18 is out, the Nextcloud website still presents the script with 16.0.3 in it....

**Comment by danielkoch** [comment]
I would raise this as critical:
1. Already fixed in Code (https://github.com/nextcloud/web-installer/blob/master/setup-nextcloud.php#L31)
2. It will ship an outdated version to new users/new installations
3. It's stated as the "... is the easiest way to install Nextcloud on a web space." on nextcloud.com

So it's only about uploading a file to the server.

**Comment by DBJRdev** [comment]
I've just checked: the setup-nextcloud.php installer script on the nextcloud.com website now says "latest" in its version number, so I guess we can safely close the issue here...

**Comment by danielkoch** [comment]
Right, looks like the version was published.
